### ISSUE TITLE
Release date : WMIEXEC and SMBEXEC 

### ISSUE THREAD

**Issue by c0d3xpl0it** [bhdresh/lazykatz#2]
Hello,

Is there are plans of implementing wimexec and smbexec in tool ?

**Comment by bhdresh** [comment]
Yes buddy, certainly. I am currently working on WMIC implementation for v3.0 which will be released in few days.

**Comment by bhdresh** [comment]
Hello,

Lazykatz v3.0-beta.2.0 is released with WMIC based authentication.
