### ISSUE TITLE
Add option download certs

### ISSUE THREAD

**Issue by PowerPress** [bhdresh/lazykatz#6]
Would love to see an option to mass download certs such as smime

**Comment by bhdresh** [comment]
Thank you @PowerPress for your comment, could you please elaborate your request?

**Comment by PowerPress** [comment]
Sure in Hack Like a Porn star book on Amazon there is a scenario where the
pentester needs to decrypt S/MIME encrypted email used by Outlook. Instead
of having to manually run Mimikatz on every workstation or a range for
example could LazyKatz provide an option to run Mimikatz and extract the
certificates from the targets and save them to the hard drive of the
pentester.

https://dragos.madarasan.com/blog/exporting-unexportable-certificates/

**Comment by bhdresh** [comment]
@PowerPress , awesome, have started working on it :)

**Comment by bhdresh** [comment]
@PowerPress, please try v4.0, your request is addressed, thanks for the suggestion :)
